### PR TITLE
make branches static

### PR DESCRIPTION
**Pull request by SimonDanisch**
I got someone running into an error with homebrew on windows... Not really sure how that exactly happened (it's from a fresh install, but I can't reproduce from a fresh one)... But hope these changes help!

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Hope it's okay if I merge this quickly, I need to get some people to not have this error ;)

**Comment by jayschwa** [comment]
@tkelman [suggested they be removed](https://github.com/JuliaGL/GLFW.jl/commit/953b72415ecdef43c9196969cb41adbd8eed9a21#commitcomment-18118898) awhile back. It's not clear to me how adding them back will fix the issue you described. Did you have the affected users run `is_windows` and `is_apple` etc from the REPL to see if it lines up with reality?

**Comment by tkelman** [comment]
you don't need at-static here, but yeah you should be checking is_apple, not Pkg.installed("Homebrew")

**Comment by SimonDanisch** [comment]
I know that they're not needed... It's just a bit of a paranoia, since once I had a bug where the `@static` in global scope was the only way to prohibit a using from executing.
I highly suspect that it was an unrelated bug, but since they don't hurt, I put them in there....

**Comment by jayschwa** [comment]
@SimonDanisch, can you point me to, or share, the exact error message the users were getting? I would expect that `os=:Darwin` option in `provides(Homebrew.HB, "glfw", glfw, os=:Darwin)` should stop it from being used on Windows, even if they had the Homebrew package installed for some reason.

**Comment by SimonDanisch** [comment]
The using created the error! It wasn't finding some environment variable that homebrew uses.

**Comment by SimonDanisch** [comment]
Btw, would it be okay to add attobot?

**Comment by jayschwa** [comment]
> Btw, would it be okay to add attobot?

Yeah, that sounds pretty convenient.

**Pull request merged**
