### PR TITLE
update to GLFW 3.3.3

### PR DESCRIPTION
**Pull request by SimonDanisch**

### CODE REVIEW

**Comment by SimonDanisch** [comment]
For osx 11 fixes. See: https://github.com/JuliaPlots/Makie.jl/issues/828

**Comment by SimonDanisch** [comment]
Binary wrapper package isn't tagged yet:
https://github.com/JuliaRegistries/General/pull/32299
Gotta try again after that is merged

**Comment by ufechner7** [comment]
What is the status of this pull request?

**Comment by SimonDanisch** [comment]
I'm waiting on @jayschwa... @jayschwa are you ok with me merging and tagging this and the other CI pr?

**Comment by jayschwa** [comment]
Feel free to make any changes without waiting for my permission. I haven't been keeping up with the Julia ecosystem.

**Pull request merged**
