### PR TITLE
Julia04 - Do not merge

### PR DESCRIPTION
**Pull request by SimonDanisch**
@jayschwa  
Hi I just wanted to discuss the changes that I made.
I guess ccall interop and adding GLFW 3.1 functionality is pretty straightforward.
But I also removed the ability to register anonymous functions and the WindowData API. I removed it mainly because I didn't get what it's supposed to do. 
It's probably something, which should be implemented at an higher level, and not spread out through the macros and ccall functions?
It cleaned up the code quite a bit, but I don't want to meddle with your package too much ;)
Best, 
Simon

### CODE REVIEW

**Comment by jayschwa** [comment]
It might be better to split some of these changes into separate pull requests. I don't want to break compatibility with Julia 0.3 until Julia 0.4 comes out. However, it's probably worth adding support for the GLFW 3.1 calls right away.

On the topic of GLFW 3.1 calls, what do you think is the best thing to do for users who are still running GLFW 3.0? In this patch, the wrapper functions will exist, but throw a `ccall` exception if called. Alternatively, the wrapper function declarations could be put behind a version check so they don't get defined for older versions. But maybe that's redundant since robust code using the package will have to do a version check anyway?

I don't want to remove support for anonymous functions as callbacks. I know the macro is ugly as sin and I'm sure it's frustrating when trying to read and understand it, but I like the convenience it enables. Being able to pass anonymous functions feels more Julian to me, and I regularly found myself wanting to do it as I built Quake2.jl.

**Comment by SimonDanisch** [comment]
> It might be better to split some of these changes into separate pull requests

Makes sense ;)

Shouldn't the updated version automatically fetch GLFW 3.1? When I did Pkg.update(), it automatically rebuild GLFW for me.
So if the user doesn't have GLFW 3.1 it should be regarded as an error, right? I don't think the supported platforms have changed, so this seems reasonable to me.

So is your only concern with my version the support for anonymous functions?
If that's the case, I think it wouldn't be hard to bring the support for anonymous functions back in a clean way. I just didn't bother, because I don't use that feature for reusability and speed reasons ;)

**Comment by SimonDanisch** [comment]
So I tried to bring back anonymous functions. If this solution works for you, i can start to split this pull request!
Best,
Simon

**Comment by jayschwa** [comment]
Please do. I haven't had time to grok or test the new callback code yet, but it looks much cleaner at face value. Nice!

I think this can be decomposed into at least 3 pull requests:
1. Cleaner callback macro
2. GLFW 3.1 support
3. Julia 0.4 updates

This will make it easier for me to test and review. I will potentially merge (1) and (2) right away (after I've kicked the tires). If (3) breaks compatibility with Julia 0.3, then it will have to stay on the sidelines for now, but at least it'll be ready to go once Julia 0.4 is released and get tested with the CI.

**Comment by SimonDanisch** [comment]
Okay, I clumsily put together the different branches, as I was a little too
impatient to properly learn rebasing.
Hope I didn't introduce any errors.

Best,
Simon

2015-04-04 18:47 GMT+02:00 Jay Weisskopf <notifications@github.com>:

**Comment by jayschwa** [comment]
Are the branches ready for review?

**Comment by SimonDanisch** [comment]
Well I'm on it for ages now, so I guess it should be mostly fine. Backward compatibility could be an issue.
By the way, it seems that there is nothing that has to be changed for the tuple breakage.

**Comment by jayschwa** [comment]
Julia 0.4 support made it in at some point.

**Pull request closed without merging**
