### PR TITLE
Various updates for Julia 0.4

### PR DESCRIPTION
**Pull request by jayschwa**

### CODE REVIEW

**Comment by SimonDanisch** [comment]
The multiwindow support does need some cooperation with ModernGL, right? We could probably just pass an additional argument which has a context id as it's parameter, so we would force it to compile a new function for each context.

**Comment by jayschwa** [comment]
Ah, good point. I hadn't considered that `glfwGetProcAddress` may return different pointers for different contexts. I just made this simple script to confirm that #63 is a real problem.

Since this module doesn't have comprehensive tests, is there a project or tools of yours I can run that uses GLFW under the hood as a sanity check? Ideally, I'd like to test this branch with something "real" before merging and tagging a new version.

**Comment by SimonDanisch** [comment]
Should I just test it? GLPlot master tests quite a bit of the functionality, but it is a little bit of a struggle to set it up correctly.

**Comment by jayschwa** [comment]
If you get a chance, that'd be great.

**Comment by SimonDanisch** [comment]
Okay, no problems on my side!
I'm at least using these:
```Julia
 GLFW.WindowHint(GLFW.CONTEXT_VERSION_MAJOR, 3)
    GLFW.WindowHint(GLFW.CONTEXT_VERSION_MINOR, 3)
    GLFW.WindowHint(GLFW.OPENGL_FORWARD_COMPAT, GL_TRUE)
    GLFW.WindowHint(GLFW.OPENGL_PROFILE, GLFW.OPENGL_CORE_PROFILE)
    GLFW.WindowHint(GLFW.OPENGL_DEBUG_CONTEXT, Cint(debugging))
    window = GLFW.CreateWindow(w, h, name)
    GLFW.MakeContextCurrent(window)
    GLFW.ShowWindow(window)
    GLFW.SetWindowCloseCallback(window, window_closed)
    GLFW.SetWindowSizeCallback(window, window_resized)
    GLFW.SetKeyCallback(window, key_pressed)
    GLFW.SetCharCallback(window, unicode_input)
    GLFW.SetMouseButtonCallback(window, mouse_clicked)
    GLFW.SetCursorPosCallback(window, cursor_position)
    GLFW.SetScrollCallback(window, scroll)
    GLFW.SetFramebufferSizeCallback(window, framebuffer_size)
    GLFW.SetWindowSize(window, w, h)
    GLFW.SetDropCallback(window, dropped_files)
```

**Comment by jayschwa** [comment]
Great, thanks :+1:

**Pull request merged**
