### PR TITLE
Added overloaded convenience properties

### PR DESCRIPTION
**Pull request by jayschwa**
TODO?:
- Do nothing when value isn't changing
- Deprecate window helper functions
- Window properties:
  - Fullscreen
  - Current context

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Is it really a good idea to use NamedTuples for the sizes/positions? Seems to me like tuples are easier to use and perfectly clear what they represent!

**Comment by SimonDanisch** [comment]
973f440f576841bc2ff6cabb05e06807a2f63b6d still works! I couldn't come up with an MWE, seems only to occur with my Makie code that registers all kinds of GLFW callbacks in a row...It's a bit involved, so not sure where exactly the closing occurs!
Sorry for spamming this PR - but since this is all prerelease, I didn't want to open an issue!

**Comment by jayschwa** [comment]
> Is it really a good idea to use NamedTuples for the sizes/positions? Seems to me like tuples are easier to use and perfectly clear what they represent!

Named tuples will only be used for output and will not be required for input. I don't think that will make the API any harder to use, and I think it will make it nicer in some cases (e.g. `window.size.width` will work).

> Sorry for spamming this PR - but since this is all prerelease, I didn't want to open an issue!

No problem, I appreciate the feedback.

**Comment by jayschwa** [comment]
> Btw, something closes the window when I register all the callbacks I need

Just so I understand, things are broken in the master branch, but the latest released version is not broken?

**Comment by jayschwa** [comment]
Is the code that triggers the bug available somewhere for me to try it?

> Well, I have now:
>
> ```
> wh = GLFW.WindowSize(window)
> tup = (wh.width, wh.height)
> ```

Named tuples should work seamlessly with code that was written for plain tuples. You can still use `wh[1]` instead of `wh.width`.

**Comment by jayschwa** [comment]
I do not plan to actively develop this package anymore.

**Pull request closed without merging**
