### PR TITLE
fix build for osx

### PR DESCRIPTION
**Pull request by jkroso**
found this fix at https://gist.github.com/vaiorabbit/6204931. It was erroring out while compiling

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Aren't you hard coding this to Mac OS 10.9 ?

**Comment by jkroso** [comment]
No according to my `man cc` it specifies the minimum version required to run the software. I'm running osx@10.10.2 at the moment

**Comment by jkroso** [comment]
Other platforms should just ignore it and the build passes so that means linux is ignoring it

**Comment by jayschwa** [comment]
Can you provide the actual error message you were getting? I'm curious since I have 10.10.2 as well and can't reproduce.

**Comment by jkroso** [comment]
```
In file included from /Users/jkroso/.julia/v0.3/GLFW/deps/src/glfw-3.0.4/src/cocoa_clipboard.m:27:
In file included from /Users/jkroso/.julia/v0.3/GLFW/deps/src/glfw-3.0.4/src/internal.h:69:
In file included from /Users/jkroso/.julia/v0.3/GLFW/deps/src/glfw-3.0.4/src/cocoa_platform.h:34:
In file included from /System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:12:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:10:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:7:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/NSRange.h:5:
/System/Library/Frameworks/Foundation.framework/Headers/NSValue.h:12:1: error: 'objc_returns_inner_pointer' attribute only applies to methods
@property (readonly) const char *objCType NS_RETURNS_INNER_POINTER;
^
```

Thats the first error it emits. There are 19 similar ones which follow before the process exits

**Comment by jayschwa** [comment]
Interesting. Hopefully it will be a moot point now. The newest version of GLFW.jl downloads pre-compiled  Homebrew binaries rather than attempting to build from source.

**Pull request closed without merging**
