### PR TITLE
fix badge

### PR DESCRIPTION
**Pull request by SimonDanisch**
...and make sure appveyor doesn't run

### CODE REVIEW

**Comment by SimonDanisch** [comment]
@jayschwa can you try to delete appveyor? For me it somehow doesn't work, and I see, that the url contains your name instead of JuliaGL when I click on appveyor here in this PR, so maybe there is something weird going on with the permissions...

**Comment by jayschwa** [comment]
I revoked AppVeyor from my personal account.

**Comment by SimonDanisch** [comment]
uh... maybe it's now in some kind of zombie state? I don't even have the settings tab when i go to the project:
https://ci.appveyor.com/project/jayschwa/glfw-jl/builds/38458768

**Comment by SimonDanisch** [comment]
I already tried adding the JuliaGL/GLFW.jl repo. That actually worked and started running the tests - but when I deleted it, it jumped back to the `project/jayschwa/glfw-jl` version -.-

**Comment by jayschwa** [comment]
Okay, now I logged into AppVeyor and deleted the project...

**Comment by SimonDanisch** [comment]
Sweet, that worked.. Thank you!

**Pull request merged**
